title: spin⠶log
email: louismmx@gmail.com
description: >
  spin⠶log is a blog starting mid-2017 aiming to focus on two
  items or concepts each day, inspired by the style of afreshcup.com
  Each day may have associated entries in related project queck⠶cal,
  and may comprise anything from a brief few words to a longer rumination
baseurl: ""
url: "http://log.spin.systems"
# twitter_username: permutans
github_username: lmmx
